apiVersion: v1
description: Helm chart for Mojaloop. This is base Dwolla code that works with postgres backend.
name: mojaloop
version: 0.2.0
home: http://mojaloop.io
icon: http://mojaloop.io/images/logo.png
sources:
  - https://github.com/mojaloop/mojaloop
  - https://github.com/mojaloop/helm
maintainers:
  - name: Miguel de Barros
    email: miguel.debarros@modusbox.com
