# requirements.yaml
dependencies:
- name: prometheus
  version: 7.3.3
  repository: https://kubernetes-charts.storage.googleapis.com
  alias: prometheus
- name: grafana
  version: 1.17.2
  repository: https://kubernetes-charts.storage.googleapis.com
  alias: grafana
