apiVersion: v1
description: Quoting-Service Helm chart for Kubernetes
name: quoting-service
version: 6.2.1
appVersion: "6.2.1-snapshot"
home: http://mojaloop.io
icon: http://mojaloop.io/images/logo.png
sources:
  - https://github.com/mojaloop/quoting-service
  - https://github.com/mojaloop/helm
  - https://github.com/mojaloop/documentation
maintainers:
  - name: Miguel de Barros
    email: miguel.debarros@modusbox.com
