{{- if .Values.service.external.enabled -}}
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ template "quotingservice.fullname" . }}
  labels:
    app: {{ template "quotingservice.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subsets: 
  -
    addresses:
      -
        ip: {{ .Values.service.external.ip }}
    ports:
      -
        port: {{ .Values.service.external.ports.api.externalPort }}
        name: {{ .Values.service.external.ports.api.name }}
{{- end -}}
