apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "centralsettlement.fullname" . }}
  labels:
    app: {{ template "centralsettlement.fullname" . }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "centralsettlement.fullname" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
{{- if .Values.global.config.affinity }}
      affinity:
{{ toYaml .Values.global.config.affinity | indent 8 }}
{{- end }}
{{- if .Values.global.config.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.global.config.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.global.config.tolerations }}
      tolerations:
{{ toYaml .Values.global.config.tolerations | indent 8 }}
{{- end }}
      {{- if .Values.init.enabled }}
      initContainers: []
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          {{- range $port := .Values.service.ports }}
            - name: {{ $port.name }}
              containerPort: {{ $port.internalPort }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: {{ .Values.service.ports.api.internalPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ .Values.service.ports.api.internalPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          {{- end }}
          env: []
          volumeMounts:
          - name: {{ template "centralsettlement.fullname" . }}-config-volume
            mountPath: /opt/central-settlement/config
      volumes:
        - name: {{ template "centralsettlement.fullname" . }}-config-volume
          configMap:
            name: {{ template "centralsettlement.fullname" . }}
            items:
            - key: default.json
              path: default.json
#            - key: knexfile.js
#              path: knexfile.js
