# requirements.yaml
dependencies:
- name: als-oracle-template-service
  version: 5.5.0
  repository: "file://./chart-template"
  condition: als-oracle-template-service.enabled
- name: als-oracle-account-service
  version: 5.5.0
  repository: "file://./chart-account"
  condition: als-oracle-account-service.enabled
