# requirements.yaml
dependencies:
- name: centralenduserregistry
  version: 0.2.0
  repository: "file://../centralenduserregistry"
  condition: centralenduserregistry.enabled
- name: mockpathfinder
  version: 0.2.0
  repository: "file://../mockpathfinder"
  condition: mockpathfinder.enabled
- name: postgresql
  version: 0.9.1
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: postgresql.enabled
