# requirements.yaml
dependencies:
- name: account-lookup-service
  version: 6.2.4
  repository: "file://./chart-service"
  condition: account-lookup-service.enabled
- name: account-lookup-service-admin
  version: 6.2.4
  repository: "file://./chart-admin"
  condition: account-lookup-service-admin.enabled
- name: percona-xtradb-cluster
  version: 0.6.4
  repository: https://kubernetes-charts.storage.googleapis.com
  alias: mysql
  condition: mysql.enabled
