# requirements.yaml
dependencies:
- name: account-lookup-service-api
  version: 5.5.0
  repository: "file://./chart-service"
  condition: account-lookup-service-api.enabled
- name: percona-xtradb-cluster
  version: 0.6.4
  repository: https://kubernetes-charts.storage.googleapis.com
  alias: mysql
  condition: mysql.enabled
