# requirements.yaml
dependencies:
- name: account-lookup-service-api
  version: 5.5.0
  repository: "file://./chart-service-api"
  condition: account-lookup-service-api.enabled
- name: account-lookup-service-admin
  version: 5.5.0
  repository: "file://./chart-service-admin"
  condition: account-lookup-service-admin.enabled
- name: percona-xtradb-cluster
  version: 0.6.4
  repository: https://kubernetes-charts.storage.googleapis.com
  alias: mysql
  condition: mysql.enabled
- name: account-oracle-service
  version: 5.5.0
  repository: "file://..//account-oracle-service"
  condition: als-oracle.enabled
