# requirements.yaml
dependencies:
  - name: centralledger-handler-bulk-transfer-prepare
    version: 7.1.0
    repository: "file://./chart-handler-bulk-transfer-prepare"
    condition: centralledger-handler-bulk-transfer-prepare.enabled
- name: centralledger-handler-bulk-transfer-fulfil
  version: 7.1.0
  repository: "file://./chart-handler-bulk-transfer-fulfil"
  condition: centralledger-handler-bulk-transfer-fulfil.enabled
- name: centralledger-handler-bulk-transfer-processing
  version: 7.1.0
  repository: "file://./chart-handler-bulk-transfer-processing"
  condition: centralledger-handler-bulk-transfer-processing.enabled
