# requirements.yaml
dependencies:
- name: fluentd-elasticsearch
  version: 4.3.2
  repository: "https://kiwigrid.github.io"
- name: elasticsearch
  version: 1.30.0
  repository: "https://kubernetes-charts.storage.googleapis.com/"
- name: kibana
  version: 3.2.3
  repository: "https://kubernetes-charts.storage.googleapis.com/"
- name: apm-server
  version: 2.1.4
  repository: "https://kubernetes-charts.storage.googleapis.com/"
