# requirements.yaml
dependencies:
#- name: centralhub
#  version: 3.4.0
#  repository: "file://../centralhub"
#  condition: centralhub.enabled
- name: centralledger
  version: 3.4.0
  repository: "file://../centralledger"
  condition: centralledger.enabled
- name: centraldirectory
  version: 2.4.0
  repository: "file://../centraldirectory"
  condition: centraldirectory.enabled
