apiVersion: v1
description: Mock-Pathfinder Helm chart for Kubernetes
name: mockpathfinder
version: 0.2.0
home: http://mojaloop.io
icon: http://mojaloop.io/images/logo.png
sources:
  - https://github.com/mojaloop/mojaloop
  - https://github.com/mojaloop/helm
  - https://github.com/mojaloop/mock-pathfinder
maintainers:
  - name: Miguel de Barros
    email: miguel.debarros@modusbox.com
