apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "als-oracle-account-service.fullname" . }}
  labels:
      app: {{ template "als-oracle-account-service.fullname" . }}
      chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
data:
  default.json: {{ (tpl (.Files.Get "configs/default.json") . ) | quote }}
  knexfile.js: {{ (tpl (.Files.Get "configs/knexfile.js") . ) | quote }}
